### PR TITLE
3821Б1ФИ3 Исаев Lab1

### PR DESCRIPTION
**Pull request by 4isper**
new file:   Mobile.h
	new file:   Phone.cpp
	new file:   Phone.h
	new file:   Simlephone.cpp
	new file:   Simlephone.h
	new file:   Smartphone.cpp
	new file:   Smartphone.h
	new file:   Source.cpp
	new file:   Stationary.cpp
	new file:   Stationary.h
	new file:   Wireless.cpp
	new file:   Wireless.h
	new file:   Wireline.cpp
	new file:   Wireline.h

### CODE REVIEW

**Comment by 4isper** [comment]
@LebedevIlyaG Здравствуйте, проверьте пожалуйста первую лабу

**Comment by 4isper** [comment]
@
4isper

**Comment by 4isper** [comment]
@4isper

**Comment by LebedevIlyaG** [comment]
Принято. 10 баллов

**Pull request merged**
